### PR TITLE
ignore unsupported section types

### PR DESCRIPTION
**Pull request by tchaikov**
Related: #6115,#11077

Signed-off-by: Kefu Chai kchai@redhat.com

### CODE REVIEW

**Comment by dmick** [comment]
Not sure about this.  We kinda want big warnings to prevent as much doc rot as we can. Maybe it's time to revisit Breathe or something else?

**Comment by tchaikov** [comment]
@dmick i tried[0] breathe. it takes 9 minutes to generate the doc. in the case of asphyxiate, it's less than 5 minutes. but we don't include build-doc in the general build process. so i guess it's fine? what do you think?

---

[0] https://github.com/tchaikov/ceph/commit/40a1ea2b33ff63cefe9aafbe5bbeafcd677f9097 , if i use sphinx 1.1.3, it takes 12 minutes for breathe to render all the docs.

**Comment by dmick** [comment]
My opinion is "go for it"; the only problem I knew of was time, and that's now close enough that I think never having to think about an unsupported comment form again is worth it.  @liewegas, do you agree?

**Comment by liewegas** [comment]
I don't think the build time is a big concern.  if breathe is better in other ways and makes things easier to maintain then let's go for it.

Note that there was a parallel discussion of building the man pages dynamically during build time, though, so hopefully we don't make that harder?  See http://marc.info/?l=ceph-devel&m=142661232101782&w=2

**Comment by dmick** [comment]
I think it can only make it better.

**Comment by liewegas** [comment]
sounds good to me!

**Pull request closed without merging**
